-- =====================================================================
-- RegRadar - Week 1 Snowflake setup
-- Run this ONCE in a Snowsight worksheet (top to bottom).
-- You need the ACCOUNTADMIN role (the person who created the account has it).
-- =====================================================================

USE ROLE ACCOUNTADMIN;

-- 1. Warehouse (the compute that runs queries). XS + auto-suspend = cheap.
CREATE WAREHOUSE IF NOT EXISTS REGRADAR_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60          -- turns off after 60 seconds idle
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

-- 2. Resource monitor (stops you from burning all your credits).
--    Change 50 to whatever credit budget your group has.
CREATE RESOURCE MONITOR IF NOT EXISTS REGRADAR_MONITOR
  WITH CREDIT_QUOTA = 50
  FREQUENCY = MONTHLY
  START_TIMESTAMP = IMMEDIATELY
  TRIGGERS
    ON 75 PERCENT DO NOTIFY
    ON 90 PERCENT DO SUSPEND
    ON 100 PERCENT DO SUSPEND_IMMEDIATE;

ALTER WAREHOUSE REGRADAR_WH SET RESOURCE_MONITOR = REGRADAR_MONITOR;

-- 3. Database and medallion schemas
CREATE DATABASE IF NOT EXISTS REGRADAR_DB;
CREATE SCHEMA IF NOT EXISTS REGRADAR_DB.BRONZE;  -- raw API data
CREATE SCHEMA IF NOT EXISTS REGRADAR_DB.SILVER;  -- Data Vault
CREATE SCHEMA IF NOT EXISTS REGRADAR_DB.GOLD;    -- Kimball star schema
CREATE SCHEMA IF NOT EXISTS REGRADAR_DB.AI;      -- chunks, embeddings, Cortex outputs
CREATE SCHEMA IF NOT EXISTS REGRADAR_DB.APP;     -- app tables, logs, eval results

-- 4. Roles
--    REGRADAR_DEV  = what the team uses day to day (full access to the project)
--    The other roles are for governance; you will tighten them in later weeks.
CREATE ROLE IF NOT EXISTS REGRADAR_DEV;
CREATE ROLE IF NOT EXISTS REGRADAR_LOADER;
CREATE ROLE IF NOT EXISTS REGRADAR_TRANSFORMER;
CREATE ROLE IF NOT EXISTS REGRADAR_APP;
CREATE ROLE IF NOT EXISTS REGRADAR_ANALYST;

-- Role hierarchy: SYSADMIN can see everything the project roles can
GRANT ROLE REGRADAR_LOADER      TO ROLE REGRADAR_DEV;
GRANT ROLE REGRADAR_TRANSFORMER TO ROLE REGRADAR_DEV;
GRANT ROLE REGRADAR_APP         TO ROLE REGRADAR_DEV;
GRANT ROLE REGRADAR_ANALYST     TO ROLE REGRADAR_DEV;
GRANT ROLE REGRADAR_DEV         TO ROLE SYSADMIN;

-- Warehouse access
GRANT USAGE, OPERATE ON WAREHOUSE REGRADAR_WH TO ROLE REGRADAR_DEV;
GRANT USAGE ON WAREHOUSE REGRADAR_WH TO ROLE REGRADAR_LOADER;
GRANT USAGE ON WAREHOUSE REGRADAR_WH TO ROLE REGRADAR_TRANSFORMER;
GRANT USAGE ON WAREHOUSE REGRADAR_WH TO ROLE REGRADAR_APP;
GRANT USAGE ON WAREHOUSE REGRADAR_WH TO ROLE REGRADAR_ANALYST;

-- Full project access for the dev role
GRANT ALL ON DATABASE REGRADAR_DB TO ROLE REGRADAR_DEV;
GRANT ALL ON ALL SCHEMAS IN DATABASE REGRADAR_DB TO ROLE REGRADAR_DEV;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE REGRADAR_DB TO ROLE REGRADAR_DEV;
GRANT ALL ON FUTURE TABLES IN DATABASE REGRADAR_DB TO ROLE REGRADAR_DEV;
GRANT ALL ON FUTURE VIEWS IN DATABASE REGRADAR_DB TO ROLE REGRADAR_DEV;

-- Narrow roles (starting point)
GRANT USAGE ON DATABASE REGRADAR_DB TO ROLE REGRADAR_LOADER;
GRANT USAGE, CREATE TABLE, CREATE STAGE ON SCHEMA REGRADAR_DB.BRONZE TO ROLE REGRADAR_LOADER;
GRANT INSERT, SELECT ON FUTURE TABLES IN SCHEMA REGRADAR_DB.BRONZE TO ROLE REGRADAR_LOADER;

GRANT USAGE ON DATABASE REGRADAR_DB TO ROLE REGRADAR_ANALYST;
GRANT USAGE ON SCHEMA REGRADAR_DB.GOLD TO ROLE REGRADAR_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA REGRADAR_DB.GOLD TO ROLE REGRADAR_ANALYST;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA REGRADAR_DB.GOLD TO ROLE REGRADAR_ANALYST;

-- Cortex AI access (needed from Week 4 onward)
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE REGRADAR_DEV;

-- OPTIONAL: if Cortex models are not available in your region, allow cross-region inference
-- ALTER ACCOUNT SET CORTEX_ENABLED_CROSS_REGION = 'ANY_REGION';

-- 5. Give yourself the dev role (replace YOUR_USERNAME)
-- GRANT ROLE REGRADAR_DEV TO USER YOUR_USERNAME;

-- 6. Create a user for each teammate (repeat for each person)
-- CREATE USER TEAMMATE1
--   PASSWORD = 'ChangeMe_123!'
--   DEFAULT_ROLE = REGRADAR_DEV
--   DEFAULT_WAREHOUSE = REGRADAR_WH
--   MUST_CHANGE_PASSWORD = TRUE;
-- GRANT ROLE REGRADAR_DEV TO USER TEAMMATE1;

-- =====================================================================
-- 7. Bronze objects (run as the dev role)
-- =====================================================================
USE ROLE REGRADAR_DEV;
USE WAREHOUSE REGRADAR_WH;
USE SCHEMA REGRADAR_DB.BRONZE;

-- File format for newline-delimited JSON (one record per line)
CREATE FILE FORMAT IF NOT EXISTS JSON_FF
  TYPE = JSON
  STRIP_OUTER_ARRAY = FALSE;

-- Internal stage = a folder inside Snowflake where raw files land
CREATE STAGE IF NOT EXISTS RAW_STAGE
  FILE_FORMAT = JSON_FF;

-- One raw table per source. Payload is the whole API record, untouched.
CREATE TABLE IF NOT EXISTS RAW_FEDERAL_REGISTER (
  PAYLOAD      VARIANT,
  SOURCE_FILE  STRING,
  LOADED_AT    TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RAW_REGULATIONS_GOV (
  PAYLOAD      VARIANT,
  SOURCE_FILE  STRING,
  LOADED_AT    TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RAW_CONGRESS (
  PAYLOAD      VARIANT,
  SOURCE_FILE  STRING,
  LOADED_AT    TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RAW_ECFR (
  PAYLOAD      VARIANT,
  SOURCE_FILE  STRING,
  LOADED_AT    TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 8. Quick Cortex test (optional). If this model isn't available, try another
--    model name from the Snowflake Cortex docs.
-- SELECT SNOWFLAKE.CORTEX.COMPLETE('llama3.1-8b', 'Say hello to the RegRadar team in one sentence.');
